# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
mvrnorm <- function(mean, Sigma) {
    .Call(`_jonnylaw_mvrnorm`, mean, Sigma)
}

#' @export
mvrnormsvd <- function(mean, Sigma) {
    .Call(`_jonnylaw_mvrnormsvd`, mean, Sigma)
}

#' @export
backwardSample <- function(g, w, mts, cts, ats, rts) {
    .Call(`_jonnylaw_backwardSample`, g, w, mts, cts, ats, rts)
}

leapfrogCpp <- function(gradient, ys, qp, stepSize) {
    .Call(`_jonnylaw_leapfrogCpp`, gradient, ys, qp, stepSize)
}

#' @export
advState <- function(g, mt, ct, w) {
    .Call(`_jonnylaw_advState`, g, mt, ct, w)
}

#' @export
oneStep <- function(ff, v, at, rt) {
    .Call(`_jonnylaw_oneStep`, ff, v, at, rt)
}

#' @export
updateState <- function(ft, at, rt, predicted, predcov, y, v) {
    .Call(`_jonnylaw_updateState`, ft, at, rt, predicted, predcov, y, v)
}

#' @export
missing_f <- function(f, y) {
    .Call(`_jonnylaw_missing_f`, f, y)
}

#' @export
missing_v <- function(v, y) {
    .Call(`_jonnylaw_missing_v`, v, y)
}

#' @export
flatten <- function(X) {
    .Call(`_jonnylaw_flatten`, X)
}

#' @export
kalmanStep <- function(yo, f, g, v, w, mt, ct) {
    .Call(`_jonnylaw_kalmanStep`, yo, f, g, v, w, mt, ct)
}

#' @export
kalmanFilter <- function(ys, f, g, v, w, m0, c0) {
    .Call(`_jonnylaw_kalmanFilter`, ys, f, g, v, w, m0, c0)
}

